### ISSUE TITLE
Error when installing (Anki 2.1.22)

### ISSUE THREAD

**Issue by MetalFir** [trgkanki/interval_booster#1]
Hey thanks for the updated add-on unfortunately I get this error when installing version: v20.11.18i164

the previous version works though 

Bug report

ebug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.16
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-11-21 22:11:37
Add-ons possibly involved: ⁨Interval booster⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 76, in handler
  File "aqt/main.py", line 195, in setupProfile
  File "</Applications/Anki 3.app/Contents/MacOS/decorator.pyc:decorator-gen-36>", line 2, in loadProfile
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 663, in repl
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/1602224446/__init__.py", line 97, in newLoadProfile
    _old(self, newOnSuccess)
  File "aqt/main.py", line 372, in loadProfile
  File "/Users/xxxxxx/Library/Application Support/Anki2/addons21/1602224446/__init__.py", line 93, in newOnSuccess
    onStartupOrSync()
  File "/Users/xxxx/Library/Application Support/Anki2/addons21/1602224446/__init__.py", line 78, in onStartupOrSync
    boostSince(time.time() - 86400 * 7)
  File "/Users/xxxxx/Library/Application Support/Anki2/addons21/1602224446/boostSince.py", line 96, in boostSince
    progress.update(value=i, max=len(cardIds))
TypeError: update() got an unexpected keyword argument 'max'

**Comment by phu54321** [comment]
Update your Anki plz.

**Comment by MetalFir** [comment]
I would but I have important add ons that only work on Anki 2.1.22 or less including 'eshapard/autoLearningSteps.py' that improve the algorithm. That are not being updated by the developer.

It's fine because ':bookmark: v20.10.12i24' works 👍


> Update your Anki plz.

**Comment by phu54321** [comment]
regarding [this article](https://www.reddit.com/r/Anki/comments/jyv7eu/supported_addons_by_anki_version/) it seems like I should support 2.1.22 as a lower margin. Will look into this

**Comment by phu54321** [comment]
Does this version work?

[build.ankiaddon.zip](https://github.com/trgkanki/interval_booster/files/5587845/build.ankiaddon.zip)

**Comment by MetalFir** [comment]
> Does this version work?
> 
> [build.ankiaddon.zip](https://github.com/trgkanki/interval_booster/files/5587845/build.ankiaddon.zip)


Sorry 😢 It says this below when trying to install.


> Error installing build.ankiaddon: Invalid add-on manifest.
> 
> Please report this to the respective add-on author(s).

**Comment by phu54321** [comment]
try this? [build.ankiaddon.zip](https://github.com/trgkanki/interval_booster/files/5589241/build.ankiaddon.zip)

**Comment by MetalFir** [comment]
> try this? [build.ankiaddon.zip](https://github.com/trgkanki/interval_booster/files/5589241/build.ankiaddon.zip)

Do you want the good news or the bad news first?


Good News: It works almost perfectly 👍

Bad News: It conflicts with the [Auto Ease Factor Add-on](https://ankiweb.net/shared/info/1672712021)  and therefore disables it when it is enabled and via versa, which an  important add-on to a number of Anki users.


Thank you for spending your time trying to fix it 👍

**Comment by phu54321** [comment]
> Bad News: It conflicts with the Auto Ease Factor Add-on and therefore disables it when it is enabled and via versa, which an important add-on to a number of Anki users.

This is intended, as this addon embeds that addon's functionalities. See [here](https://github.com/brownbat/autoEaseFactor/issues/17).

**Comment by MetalFir** [comment]
> > Bad News: It conflicts with the Auto Ease Factor Add-on and therefore disables it when it is enabled and via versa, which an important add-on to a number of Anki users.
> 
> This is intended, as this addon embeds that addon's functionalities. See [here](https://github.com/brownbat/autoEaseFactor/issues/17).

 It works perfectly then.

**Comment by MetalFir** [comment]
> > Bad News: It conflicts with the Auto Ease Factor Add-on and therefore disables it when it is enabled and via versa, which an important add-on to a number of Anki users.
> 
> This is intended, as this addon embeds that addon's functionalities. See [here](https://github.com/brownbat/autoEaseFactor/issues/17).

**One** last small thing if it's not too much trouble. 

Would it be possible to inform me how to integrate back YesorNo.py. from 'auto ease factor'? 

It's not a big deal at all but I prefer a pass/fail 2 button solution. 


**Edit: Nevermind I've managed to do it**

**Comment by phu54321** [comment]
OK closing this
